version: '3'
services:
        #  bench:
        #    build:
        #      context: ./docker/bench
        #      args:
        #        GIT_URL: https://github.com/isucon/isucon7-qualify.git
        #    image: isucon7-qualifier-bench
        #    depends_on:
        #      - web
        #    networks:
        #      - frontend
        #  web:
        #    build:
        #      context: ./docker/web
        #      args:
        #        GIT_URL: https://github.com/isucon/isucon7-qualify.git
        #    image: isucon7-qualifier-web:nginx
        #    networks:
        #      - frontend
        #      - backend
        #    depends_on:
        #      - app
        #    ports:
        #      - "80:80"
  app:
    build:
      context: ./docker/app/golang
      args:
              #        GIT_URL: https://github.com/isucon/isucon7-qualify.git
        GIT_URL: git@github.com:jp-taku2/testa.git
              #        WORK_DIR: isubata
    image: isucon7-qualifier-app:golang
    volumes:
            - /home/jp_taku/work/testa/webapp/go:/home/isucon/isubata/webapp/go
    networks:
      - frontend
        #    depends_on:
        #        - db
    ports:
            - "80:5000"
    environment:
      ISUBATA_DB_USER: isucon
      ISUBATA_DB_PASSWORD: isucon
      ISUBATA_DB_HOST: 52.194.251.237
      #  db:
      #    build:
      #      context: ./docker/db
      #      args:
      #        GIT_URL: https://github.com/isucon/isucon7-qualify.git
      #    image: isucon7-qualifier-db
      #    ports:
      #      - "3306"
      #    networks:
      #      - backend
      #    command: ["--character-set-server=utf8mb4"]
      #    environment:
      #      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      #      MYSQL_DATABASE: isubata
      #      MYSQL_USER: isucon
      #      MYSQL_PASSWORD: isucon
networks:
  frontend:
  backend:
