version: '3'
services:
  web:
    build:
      context: ./docker/web
    image: isucon8-qualifier-web
    depends_on:
    - app
    networks:
    - frontend
    - backend
    ports:
    - "80:80"
    volumes:
    - ./docker/web/default-h2o.conf:/etc/h2o/h2o.conf

  app:
    build:
      context: ./docker/app/golang
      args:
        GIT_URL: https://github.com/jp-taku2/isucon8.git
        #        WORK_DIR: isubata
    image: isucon8-qualifier-app:golang
    #    volumes:
            #    - $HOME/work/isucon8/webapp:/home/isucon/torb/webapp
    depends_on:
    - db
    networks:
    - backend
    ports:
    - "8080"
    environment:
      DB_DATABASE: torb
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: isucon
      DB_PASS: isucon
  db:
    build:
      context: ./docker/db
      args:
        GIT_URL: https://github.com/jp-taku2/isucon8.git
    image: isucon8-qualifier-db
    networks:
    - backend
    ports:
    - "3306"
    command: ["--character-set-server=utf8mb4"]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: torb
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
networks:
  frontend:
  backend:
